In [1]:
import numpy as np

In [6]:
l1 = np.random.randn(2,2,2)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
#l1[row,col]
# np.random.rand[create dimension as well]

[[[ 0.52235783 -1.13740527]
  [-1.02147063  0.06598809]]

 [[ 0.03109187  0.04953583]
  [-1.61907926 -1.49058579]]]
Dimension: 3
Shape: (2, 2, 2)
Type: float64


In [12]:
l1 = np.arange(5)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
#l1[row,col]
# np.arange[just range function]

[0 1 2 3 4]
Dimension: 1
Shape: (5,)
Type: int32


<h3> reshape </h3>

In [8]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
l1[1,2,1] # location found there would be 16



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension: 3
Shape: (3, 3, 3)
Type: int32


16

<h4> A Multidimensional Array Object¶ </h4>


In [ ]:
# before we use rand.rand was also multi dimension that was just for showing difference with arrange

In [13]:
l1 = np.arange(1,11) # its a one dim
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1
Shape: (10,)
Type: int32


In [17]:
# let we change it
l1=np.arange(1,28).reshape(3,9)
print(l1)
print(l1.ndim)
print(l1.shape)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
2
(3, 9)


In [19]:
l1 = np.random.randn(3,3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("itemsize", l1.itemsize)
print("Type:", l1.dtype)

[[[[ 0.69392948 -0.92977469 -1.41866694]
   [-0.94512354  1.94200489 -1.0577283 ]
   [-0.14462853 -0.64840389  0.03464245]]

  [[-0.89509976 -0.17056292 -1.27512575]
   [-2.09555026  0.05184161  1.59718936]
   [-1.85050371 -0.29032416 -1.13662248]]

  [[ 0.21235389  0.06765531  1.30821148]
   [ 1.10628936 -0.41734772  0.27199003]
   [ 0.91969041  1.32015514  0.03751424]]]


 [[[ 0.83456697  1.08581199 -0.94768131]
   [ 0.03591415  1.15906201  0.42845293]
   [ 0.57841886  0.7072145  -0.98667558]]

  [[-1.96844257 -0.60490887  0.46781951]
   [ 0.64998009 -0.73553301  0.41753239]
   [ 0.76690075  1.10307434 -0.16852879]]

  [[ 0.35717037 -0.38280816 -1.32342533]
   [ 1.38890205  0.89066938  1.94408601]
   [ 0.28125846 -0.08953326 -1.02266083]]]


 [[[-0.41401338 -0.98403961  0.77432689]
   [-0.17679696  0.20292672 -0.30992583]
   [-0.8755839   2.05389702 -1.77184953]]

  [[-0.10587111 -1.24590813 -0.1081832 ]
   [-0.92588306 -0.06596467 -0.43993477]
   [ 0.97159166  0.17346968 -0.1526114 

In [27]:
a= np.arange(1,28).reshape(3,3,3)
print(a)
print(a * .5)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 0.5  1.   1.5]
  [ 2.   2.5  3. ]
  [ 3.5  4.   4.5]]

 [[ 5.   5.5  6. ]
  [ 6.5  7.   7.5]
  [ 8.   8.5  9. ]]

 [[ 9.5 10.  10.5]
  [11.  11.5 12. ]
  [12.5 13.  13.5]]]


#  np.array

In [34]:
# Deep Copy
l = [1,2,3]
print(l)
print(type(l))

a = np.array(l)
print(type(a))
b = np.array(a)
print(type(b))

print(a is b)
print(a is l)
print(b)


[1, 2, 3]
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
False
False
[1 2 3]


# nd array

In [37]:
# 1 array->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #2
print(type(a))
print(a is l)

b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#3

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)


<class 'list'>
<class 'numpy.ndarray'>
False
True
False
False


numpy.ndarray

# slicing

In [39]:

a=np.arange(3*3*3).reshape(3,3,3)
print(a)
a.ndim

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


3

In [47]:
#slicing
print(a[1:1:2])
print(a[-2,1,2])
print(a[1][1][2])
a[1,1,2]

[]
14
14


14

In [10]:
a[[-1,-2,-3],:,]  #: for full
#also  
print(a[[-1,-2,-3]])
print(a[-1,-2,-3]) #bcz single dimension given reprent 21

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
21


In [55]:
names = np.array([["Qasim","Hamza","Ali","Junaid","Qasim","Ali"]])

data = np.random.randn(6,4)
print(names, data, sep="\n")

[['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']]
[[ 1.47032665 -0.26305746  0.17816787 -0.84284959]
 [-0.16214352  1.05377334 -0.73666977 -0.42173392]
 [-0.46883831  0.75667537 -0.67674802  1.61347849]
 [ 0.65243226 -0.88142732 -0.01209765 -1.21298642]
 [ 0.3560491   1.02014612 -1.09533445 -0.12576202]
 [-0.26656064 -1.55671234  0.97300754  0.34784484]]


In [56]:
names=='Hamza'

array([[False,  True, False, False, False, False]])

In [57]:
data[[True,False,True,False,True,True]]

array([[ 1.47032665, -0.26305746,  0.17816787, -0.84284959],
       [-0.46883831,  0.75667537, -0.67674802,  1.61347849],
       [ 0.3560491 ,  1.02014612, -1.09533445, -0.12576202],
       [-0.26656064, -1.55671234,  0.97300754,  0.34784484]])

In [62]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)
print(names, data, sep="\n")
data[names=='Ali']

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 0.47650108 -0.41948782  1.90467383  0.71014603]
 [ 0.50362465 -0.53427167  0.03236248 -0.77222903]
 [ 0.18909784 -0.89812284  0.2436205   0.35736729]
 [ 0.65897239 -1.84126828  1.4854939  -0.74667488]
 [-1.1724676  -0.05076801  1.03265937  1.44286545]
 [-1.78125675 -1.26016243  0.15667617  2.23471363]]


array([[ 0.18909784, -0.89812284,  0.2436205 ,  0.35736729],
       [-1.78125675, -1.26016243,  0.15667617,  2.23471363]])

In [64]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)

print(names, data, sep="\n")

data[names=="Qasim"][1:,[-1,0,2]] # qasim name rows first see and then pick only row 1 where having six values, so pick only -1,0,2

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 0.22681473 -0.33496689  0.63166693  1.01426205]
 [-2.30501751 -0.74878377 -0.17335625 -1.36802151]
 [-0.25895778  0.10092584  0.20508259 -0.74758432]
 [ 1.41871447  0.31281232 -0.84992475 -0.11966721]
 [-1.53775529  1.26655039 -0.62532683 -0.61340695]
 [-0.52367596  1.39322595  0.48221208 -0.37125011]]


array([[-0.61340695, -1.53775529, -0.62532683]])

In [70]:
print(data[names=='Ali'])
print(data[names=='Ali'][-1])
data[names=='Ali'][-1:,[0,1]]

[[-0.25895778  0.10092584  0.20508259 -0.74758432]
 [-0.52367596  1.39322595  0.48221208 -0.37125011]]
[-0.52367596  1.39322595  0.48221208 -0.37125011]


array([[-0.52367596,  1.39322595]])

In [71]:
data[names=='Ali'][:,[0,1]] #all rows with 0,1 value

array([[-0.25895778,  0.10092584],
       [-0.52367596,  1.39322595]])

In [74]:
data[(names != "Qasim") | (names!="Ali")]
#data[:,::-1]

array([[ 0.22681473, -0.33496689,  0.63166693,  1.01426205],
       [-2.30501751, -0.74878377, -0.17335625, -1.36802151],
       [-0.25895778,  0.10092584,  0.20508259, -0.74758432],
       [ 1.41871447,  0.31281232, -0.84992475, -0.11966721],
       [-1.53775529,  1.26655039, -0.62532683, -0.61340695],
       [-0.52367596,  1.39322595,  0.48221208, -0.37125011]])

# Fancy Slicing

In [76]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



In [84]:
a  = np.arange(3*3*3).reshape(3,3,3)

print(a[[-1,-2,0],:,:])
print('gap')
print(a[-1,-2,0]) #will give oly 21
print('gap')
print(a[[-1,-2,0]])


[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
gap
21
gap
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [89]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()
print(a[:,[1,2], :])
#print(a[:,0:, :])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[ 3  4  5]
  [ 6  7  8]]

 [[12 13 14]
  [15 16 17]]

 [[21 22 23]
  [24 25 26]]]


In [91]:
a[1]=5
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 5,  5,  5],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
a = np.arange(3*3).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
g=a[1:,1:,] # 1 ky bad sari
print(g)
p=a[1:3,1:3]
p

[[4 5]
 [7 8]]


array([[4, 5],
       [7, 8]])

In [106]:
a=np.arange(3*8).reshape(3,8)
a
for i in range(len(a)):
    a[i]=i
    
print(a)    

[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]]


In [107]:
a = np.arange(8*4).reshape((8,4))
print(a)
a[[5,4,3]][:,[3,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[23, 21],
       [19, 17],
       [15, 13]])

In [108]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [ ]:
deep copy ky lye function .copy lgana hoga. ix ma pysical copy krna hota

In [11]:
a[:2:1]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [13]:
b= np.arange(3*3).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
b[1:,1:]

array([[4, 5],
       [7, 8]])

In [25]:
aar=np.array(['Qasim','Hamza','Ali','Junaid','Qasim','Ali'])
data=np.random.rand(6,4)
print(aar, data, sep='\n')
data[(aar=='Qasim')|(aar=='Ali')]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[0.60334284 0.19598316 0.2541959  0.34780081]
 [0.67618149 0.70863475 0.91471976 0.75250399]
 [0.48707557 0.56090109 0.86374413 0.49075877]
 [0.36346411 0.35287162 0.9260888  0.54773355]
 [0.43052391 0.83334811 0.85366667 0.59416479]
 [0.81162537 0.09090456 0.57409554 0.27342376]]


array([[0.60334284, 0.19598316, 0.2541959 , 0.34780081],
       [0.48707557, 0.56090109, 0.86374413, 0.49075877],
       [0.43052391, 0.83334811, 0.85366667, 0.59416479],
       [0.81162537, 0.09090456, 0.57409554, 0.27342376]])

# Transposing Arrays and Swapping Axes¶


In [109]:
a = np.arange(4*3).reshape((4,3))
print(a)
print(a.T)
print(a.transpose())


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [110]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a * b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[ 3  8]
 [15 24]]


In [111]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a @ b) #dot product

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [112]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a.dot(b))


[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [113]:
a

array([[1, 2],
       [3, 4]])

In [114]:
a.T

array([[1, 3],
       [2, 4]])

In [116]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [117]:
a@(a.T)

array([[ 5, 11],
       [11, 25]])

In [118]:

a = np.arange(27).reshape((3,3,3))
print(a)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [119]:
a.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [123]:
print(a)
print(a.transpose((0,2,1)))


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  3  6]
  [ 1  4  7]
  [ 2  5  8]]

 [[ 9 12 15]
  [10 13 16]
  [11 14 17]]

 [[18 21 24]
  [19 22 25]
  [20 23 26]]]


In [124]:
a = np.arange(12).reshape(4,3)
print(a)
print(a.swapaxes(1,0))
#print(a.reshape((a.shape[1], a.shape[0])))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


# 4.2 Universal Functions: Fast Element-Wise Array Functions¶


In [125]:
l = np.array([-1,3,-5,8,0])
np.abs(l)

array([1, 3, 5, 8, 0])

In [126]:
l = np.array([-1,3,-5,8,0])
np.fabs(l)


array([1., 3., 5., 8., 0.])

In [127]:
np.sqrt([36,25,9])


array([6., 5., 3.])

In [128]:
np.square([2,3,4])


array([ 4,  9, 16], dtype=int32)

In [129]:
np.exp([2,3,5])


array([  7.3890561 ,  20.08553692, 148.4131591 ])

In [130]:
np.ceil([2.2, 3.1, 2.6])


array([3., 4., 3.])

In [131]:
np.floor([2.2, 3.1, 2.6])


array([2., 3., 2.])

In [133]:
a = np.array([2.2, 3.1, 2.6])
print(a)
print()
f, w = np.modf(a)
print(w,f, sep="\n\n")

[2.2 3.1 2.6]

[2. 3. 2.]

[0.2 0.1 0.6]


In [134]:
for i in [2.2, 3.1, 2.6]:
    i= str(i).split(".")
    print(i[0], i[1])

2 2
3 1
2 6


In [136]:
a = np.array([1,3,45])
b = np.array([2,4,3])
np.maximum(a,b)

array([ 2,  4, 45])

In [137]:
np.fmax(a,b)


array([ 2,  4, 45])

In [141]:
a = np.arange(2*2).reshape((2,2))
print(a)
np.meshgrid(a,a)  #first combine all in one row, then write all one by one in complete line

[[0 1]
 [2 3]]


[array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]), array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])]

# Expressing Conditional Logic as Array Operations¶


In [142]:
a = np.arange(3*3*3).reshape((3,3,3))
a %3 == 0


array([[[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]]])

In [143]:
np.where(a%3==0, "Yes","No")


array([[['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']]], dtype='<U3')

In [144]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.where(a>b, a, b))

[ 2  4 45]
