In [ ]:
# Ut from eng qasim/saylani for numpy

In [38]:
import numpy as np
a = np.random.randint(1, 20, size=20)# if not pass size than will give only 1 number its randint but rando.randn is differ
b = np.random.randint(1, 10, size=10)
print(a, b, sep='\n\n')


[12  7 17 17 11 10  6  9 13  6 18  7 11 19 11 19 19 13 19  5]

[4 2 2 2 6 3 9 4 4 7]


In [42]:
[True if x in a else False for x in b] #b ma jo jo a h.wha true


[False, False, False, False, True, False, True, False, False, True]

In [45]:
#with numpy
np.in1d(b,a)

array([False, False, False, False,  True, False,  True, False, False,
        True])

# today stacking, split and imp function

# Stacking

In [ ]:
stacking= combine of array

In [3]:
import numpy as np
a= np.arange(1,7)
b= a+5
print(a, b, sep='\n')

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


In [47]:
a=np.arange(1,5)
b=a*4
print(a,b,sep='\n\n')
np.stack((a,b))# single bracket will issue here.and if axis not pass would be row base for e.g here below

[1 2 3 4]

[ 4  8 12 16]


array([[ 1,  2,  3,  4],
       [ 4,  8, 12, 16]])

In [ ]:
# axis=o, top to botom combine...mean row
# axis=1 left to right, mean column wise

In [48]:
a= np.arange(1,7)
b= a+5
print(a, b, sep='\n')
np.stack((a,b),axis=0)

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [49]:
np.stack((a,b),axis=1)#column wise

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

#hstack= horizaontal stack, dono ko aik kr dya. one m.
#vstack.. yea verticla stack 
#axis=0, vstack and rowstack give same ans.. top to bottom combine jhory ga


#np.block[a,b] sim like hstack and col stack

# deep stack. 
#must have more than two dim array

In [59]:
a=np.arange(1,10).reshape(3,3)
b=a*5
np.dstack((a,b))

array([[[ 1,  5],
        [ 2, 10],
        [ 3, 15]],

       [[ 4, 20],
        [ 5, 25],
        [ 6, 30]],

       [[ 7, 35],
        [ 8, 40],
        [ 9, 45]]])

In [61]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 10
print(a, b , sep='\n\n')
print('gap')
np.dstack((a,b))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]
gap


array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

# horizontal stack

In [52]:
np.hstack((a,b)) #combine both

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

# verticle_stack

In [53]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
a=np.arange(2*2).reshape(2,2)
b=a+5
print(a,b,sep='\n\n')

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


In [68]:
np.full_like(a,5)


array([[5, 5],
       [5, 5]])

In [69]:
np.column_stack((a,b))

array([[0, 1, 5, 6],
       [2, 3, 7, 8]])

In [70]:
np.row_stack((a,b))

array([[0, 1],
       [2, 3],
       [5, 6],
       [7, 8]])

# broadcasting

In [7]:
#dimension must be same. for adding, dono ki dimension same ho
a= np.random.randint(1,10,size=(3,5))

In [8]:
a+5

array([[10, 11,  7, 13, 12],
       [10,  9, 11, 12,  6],
       [11,  8, 12, 13, 11]])

# split

In [73]:
np.random.randn(1,10)

array([[ 1.86501766,  0.97388541,  0.46869607,  1.19468834,  1.30367097,
         0.03147849,  0.61630754, -1.56515727,  0.10250371,  0.04737302]])

In [90]:
a=np.arange(1,28) #size not give hereonly in randint
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [91]:
np.split(a,3)

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
 array([19, 20, 21, 22, 23, 24, 25, 26, 27])]

In [92]:
a=np.arange(6*6).reshape(6,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [97]:
np.split(a,3, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [11]:
np.split(a,2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [13]:
np.split(a,5, axis=0) # 5 not possible

ValueError: array split does not result in an equal division

In [14]:
np.split(a,2, axis=1) # col

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [15]:
np.split(a,6, axis=1) # col

[array([[ 0],
        [ 6],
        [12],
        [18],
        [24],
        [30]]), array([[ 1],
        [ 7],
        [13],
        [19],
        [25],
        [31]]), array([[ 2],
        [ 8],
        [14],
        [20],
        [26],
        [32]]), array([[ 3],
        [ 9],
        [15],
        [21],
        [27],
        [33]]), array([[ 4],
        [10],
        [16],
        [22],
        [28],
        [34]]), array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]])]

In [ ]:
dsplit 
np.split

# imp methods

In [100]:
a=np.random.randint(1,15,size=(14))
b=np.random.randint(10,14,size=5)
print(a,b,sep='\n')

[ 5 11 10  4 11 11  7 11 10 14  6  2  3  8]
[11 10 13 12 13]


In [101]:
#intersection
np.intersect1d(a,b)

array([10, 11])

In [17]:
#unique
a= np.random.randint(1,10, size=20)
print(a)
np.unique(a)

[8 4 1 1 9 9 9 7 9 7 4 3 6 5 7 3 9 7 8 6]


array([1, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a= np.random.randint(1,10, size=20)
print(a)
b= np.random.randint(1,10, size=5)
print(b)

[5 6 3 6 9 3 4 5 8 7 9 8 9 1 2 7 8 1 8 2]
[8 1 1 5 1]


In [ ]:
# b compare with a, each and each elemnt

In [20]:
[True if x in a else False for x in b]

[True, True, True, True, True]

In [22]:
np.in1d(b,a) # in place of python code we use numpy function , rspnse same like array with b

array([ True,  True,  True,  True,  True])

In [ ]:
now to check thier values what are they

In [23]:
np.intersect1d(b,a) # intersect jo dono ma commn ho

array([1, 5, 8])

In [105]:
np.union1d(b,a)

array([ 2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14])

In [25]:
np.setdiff1d(b,a) # jo b ky a m ni mily unki list.

array([], dtype=int32)

In [ ]:
#Xor
# justprovide 1 when having both differ
0 1= 1
1 0=1
#aexy customer jo srf feb and jan m login

In [26]:
np.setxor1d(b,a)

array([2, 3, 4, 6, 7, 9])

In [ ]:
# deeplearning from course era
neural network and deepl learning
# all these  from book chapter 4, 4.4
# explore uit and saylani-a.i repository on enggqasim


# pandas

In [ ]:
pandas= tabuler data, mean row, col
series=1 col,
dataframe= whole 

In [ ]:
utf8. multiple language suuport eng, chinese, same like ascii
pass in readcsv afterfile link, encoding='cp1252' or utf-8
usecols=['C','A'] mean srf csv xy yea ly
# titanic data explore

In [ ]:
Excel
sheet name 
pic by string name(sheet_1 or 2) or indexing
sheet_name='sheet1'
pdf read ky lye tabula
after machine learning algo can store in pixel frame
can also store in sql format

In [ ]:
one column. 
df.Colname

In [ ]:
Advantages of series


In [29]:
import pandas as pd
obj= pd.Series([1,2,4,5])
print(obj)

0    1
1    2
2    4
3    5
dtype: int64


In [ ]:
array and series same but we can change index of series but not array.
two imp things in series index, range

In [30]:
obj.index #strts at 0

RangeIndex(start=0, stop=4, step=1)

In [32]:
obj.values

array([1, 2, 4, 5], dtype=int64)

In [ ]:
now to replace its index and whats benefit

In [ ]:
benefit = jo match ho ry add, baqi Nan from two series
index ka name b change ho sakta. o jo index set kiye unki values next time pta hon gi